name: Production deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Run CI command
  #       run: npm ci
  #     - name: Run the tests
  #       run: npm run test
  build:
    # needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run CI command
        run: npm ci
      - name: Build
        run: npm run build
